export const mockProducts = [
  {
    id: 1,
    name: "iPhone 17 Pro Max 256GB | Chính hãng",
    image:
      "https://cdn2.cellphones.com.vn/insecure/rs:fill:300:300/q:100/plain/https://cellphones.com.vn/media/catalog/product/i/p/iphone-17-pro-max_3.jpg",
    currentPrice: "35.990.000₫",
    oldPrice: "37.990.000₫",
    discountPercent: "Giảm 5%",
    installment: "Trả góp 0%",
    promos: [{ text: "Smember giảm đến 360.000đ", type: "blue" }],
    note: "Trả góp 0% - 0đ phụ phí - 0đ trả trước - kỳ hạn đến 6 tháng",
    delivery: "2 Giờ",
    rating: 5,
  },
  {
    id: 2,
    name: "Samsung Galaxy S26 Ultra 5G 12GB 256GB",
    image:
      "https://cdn2.cellphones.com.vn/insecure/rs:fill:358:358/q:90/plain/https://cellphones.com.vn/media/catalog/product/s/s/ss-s24-ultra-xam-222.png",
    currentPrice: "30.890.000₫",
    oldPrice: "36.990.000₫",
    discountPercent: "Giảm 16%",
    installment: "Trả góp 0%",
    promos: [
      { text: "Smember giảm đến 309.000đ", type: "blue" },
      { text: "S-Student giảm thêm 500.000đ", type: "purple" },
    ],
    note: "Trả góp 0% - 0đ phụ phí - 0đ trả trước - kỳ hạn đến 12 tháng",
    delivery: "2 Giờ",
    rating: 5,
  },
  {
    id: 3,
    name: "OPPO Find X9 Ultra 12GB 512GB",
    image:
      "https://cdn2.cellphones.com.vn/insecure/rs:fill:300:300/q:100/plain/https://cellphones.com.vn/media/catalog/product/s/a/samsung-galaxy-a07-5g-2_3.jpg",
    currentPrice: "48.990.000₫",
    oldPrice: "49.990.000₫",
    discountPercent: "Giảm 2%",
    installment: "Trả góp 0%",
    promos: [
      { text: "Smember giảm đến 490.000đ", type: "blue" },
      { text: "S-Student giảm thêm 300.000đ", type: "purple" },
    ],
    note: "Trả góp 0% - 0đ phụ phí - 0đ trả trước - kỳ hạn đến 12 tháng",
    delivery: "2 Giờ",
    rating: 5,
  },
  {
    id: 4,
    name: "Samsung Galaxy Z Fold7 12GB 256GB",
    image:
      "https://cdn2.cellphones.com.vn/insecure/rs:fill:300:300/q:100/plain/https://cellphones.com.vn/media/catalog/product/i/p/iphone-17-pro-max_3.jpg",
    currentPrice: "41.990.000₫",
    oldPrice: "46.990.000₫",
    discountPercent: "Giảm 11%",
    installment: "Trả góp 0%",
    promos: [
      { text: "Smember giảm đến 420.000đ", type: "blue" },
      { text: "S-Student giảm thêm 500.000đ", type: "purple" },
    ],
    note: "Trả góp 0% - 0đ phụ phí - 0đ trả trước - kỳ hạn đến 12 tháng",
    delivery: "2 Giờ",
    rating: 5,
  },
  {
    id: 5,
    name: "Samsung Galaxy Z Fold7 12GB 256GB",
    image:
      "https://cdn2.cellphones.com.vn/insecure/rs:fill:300:300/q:100/plain/https://cellphones.com.vn/media/catalog/product/x/i/xiaomi-redmi-note-14-pro-plus.jpg",
    currentPrice: "41.990.000₫",
    oldPrice: "46.990.000₫",
    discountPercent: "Giảm 11%",
    installment: "Trả góp 0%",
    promos: [
      { text: "Smember giảm đến 420.000đ", type: "blue" },
      { text: "S-Student giảm thêm 500.000đ", type: "purple" },
    ],
    note: "Trả góp 0% - 0đ phụ phí - 0đ trả trước - kỳ hạn đến 12 tháng",
    delivery: "2 Giờ",
    rating: 5,
  },
  {
    id: 6,
    name: "Samsung Galaxy Z Fold7 12GB 256GB",
    image:
      "https://cdn2.cellphones.com.vn/insecure/rs:fill:300:300/q:100/plain/https://cellphones.com.vn/media/catalog/product/s/a/samsung-galaxy-s26-10.jpg",
    currentPrice: "41.990.000₫",
    oldPrice: "46.990.000₫",
    discountPercent: "Giảm 11%",
    installment: "Trả góp 0%",
    promos: [
      { text: "Smember giảm đến 420.000đ", type: "blue" },
      { text: "S-Student giảm thêm 500.000đ", type: "purple" },
    ],
    note: "Trả góp 0% - 0đ phụ phí - 0đ trả trước - kỳ hạn đến 12 tháng",
    delivery: "2 Giờ",
    rating: 5,
  },
  {
    id: 7,
    name: "Samsung Galaxy Z Fold7 12GB 256GB",
    image:
      "https://cdn2.cellphones.com.vn/insecure/rs:fill:300:300/q:100/plain/https://cellphones.com.vn/media/catalog/product/s/a/samsung-galaxy-z-fold-7.jpg",
    currentPrice: "41.990.000₫",
    oldPrice: "46.990.000₫",
    discountPercent: "Giảm 11%",
    installment: "Trả góp 0%",
    promos: [
      { text: "Smember giảm đến 420.000đ", type: "blue" },
      { text: "S-Student giảm thêm 500.000đ", type: "purple" },
    ],
    note: "Trả góp 0% - 0đ phụ phí - 0đ trả trước - kỳ hạn đến 12 tháng",
    delivery: "2 Giờ",
    rating: 5,
  },
  {
    id: 8,
    name: "Samsung Galaxy Z Fold7 12GB 256GB",
    image:
      "https://cdn2.cellphones.com.vn/insecure/rs:fill:300:300/q:100/plain/https://cellphones.com.vn/media/catalog/product/d/i/dien-thoai-oppo-find-x9-ultra-cam-8.jpg",
    currentPrice: "41.990.000₫",
    oldPrice: "46.990.000₫",
    discountPercent: "Giảm 11%",
    installment: "Trả góp 0%",
    promos: [
      { text: "Smember giảm đến 420.000đ", type: "blue" },
      { text: "S-Student giảm thêm 500.000đ", type: "purple" },
    ],
    note: "Trả góp 0% - 0đ phụ phí - 0đ trả trước - kỳ hạn đến 12 tháng",
    delivery: "2 Giờ",
    rating: 5,
  },
];
